trigger:
- main

resources:
  repositories:
  - repository: templates
    type: github
    name: JeringTech/DevOps.AzurePipelines
    endpoint: JeringTech

jobs:
- template: templates/nuget/main.yml@templates
  parameters:
    codecovKey: "67424e1a-1c96-4db4-8874-bfa35e2d302c"
- template: templates/docs/main.yml@templates
  parameters:
    nugetRestorePats: "$(nugetRestorePats)"
